[build-system]
requires = ["setuptools >= 80", "setuptools-scm >= 8.2"]
build-backend = "setuptools.build_meta"

[project]
name = "Mopidy-Podcast-iTunes"
description = "Mopidy extension for searching and browsing podcasts on Apple Podcasts"
authors = [
    {name = "Thomas Kemmer", email = "tkemmer@computer.org"}
]
maintainers = [
    {name = "Thomas Kemmer", email = "tkemmer@computer.org"}
]
readme = "README.rst"
license = "Apache-2.0"
license-files = ["LICENSE"]
requires-python = ">= 3.13"
classifiers = [
    "Environment :: No Input/Output (Daemon)",
    "Intended Audience :: End Users/Desktop",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Multimedia :: Sound/Audio :: Players",
]
dependencies = [
    "mopidy >= 4.0.0",
    "mopidy-podcast >= 4.0.0",
    "pykka >= 4.1",
    "requests >= 2.32"
]
dynamic = ["version"]

[project.entry-points."mopidy.ext"]
podcast-itunes = "mopidy_podcast_itunes:Extension"

[project.urls]
Homepage = "https://github.com/tkem/mopidy-podcast-itunes/"
Documentation = "https://mopidy-podcast-itunes.readthedocs.io/en/stable/"
Source = "https://github.com/tkem/mopidy-podcast-itunes/"
Repository = "https://github.com/tkem/mopidy-podcast-itunes/"
Issues = "https://github.com/tkem/mopidy-podcast-itunes/issues"
Changelog = "https://github.com/tkem/mopidy-podcast-itunes/blob/master/CHANGELOG.rst"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
"*" = ["*.conf"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
version = {attr = "mopidy_podcast_itunes.__version__"}

[tool.pyright]
typeCheckingMode = "standard"
#reportFunctionMemberAccess = false
#reportOptionalContextManager = false
#reportOptionalMemberAccess = false
